"""Remove Review relationships

Revision ID: 20a1ba3c3b04
Revises: a8d5242a4f1e
Create Date: 2025-10-04 11:55:54.766214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a1ba3c3b04'
down_revision: Union[str, None] = 'a8d5242a4f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
