"""Fix relationship names and model issues

Revision ID: 3e7f9b3c9bd7
Revises: 6d313eea8752
Create Date: 2025-10-04 10:57:53.832971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e7f9b3c9bd7'
down_revision: Union[str, None] = '6d313eea8752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
