"""Add cart and cart_item tables

Revision ID: 4293277e752d
Revises: c6c6fafd287d
Create Date: 2025-10-06 16:34:32.241888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4293277e752d'
down_revision: Union[str, None] = 'c6c6fafd287d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
