"""Remove relationships temporarily

Revision ID: 89908770df11
Revises: 3e7f9b3c9bd7
Create Date: 2025-10-04 11:30:26.191806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89908770df11'
down_revision: Union[str, None] = '3e7f9b3c9bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
