"""Add cart and cart_item tables

Revision ID: c6c6fafd287d
Revises: 3fc99685f47d
Create Date: 2025-10-06 16:31:18.023731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c6fafd287d'
down_revision: Union[str, None] = '3fc99685f47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
